apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
  namespace: miniflux
spec:
  instances: 1
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: miniflux
      owner: miniflux
