---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-admin
  namespace: miniflux
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCq2C3dr7Rt9QF0wQe0//PEB9t5zBkXyRQsxYhA9iWzQAdDFgD2dmSv0c2/pLAIFCILSo3hEGBtzoW0U+yfWQV0u9rF5MyvQbCvx1ezvOzP3Y8GcZ9cmAsIhhTrE7+cLEo3NqWPD4E0O2cfhCSAbaL/zyWk507fJSqNtiD5wE1FLvN3OlnUP/tBZL+aTcg+s+GJmlFn3Fq8MQ9e1kdaGGio+FTMuZgMl12Bw7fnoSrbLn34UUF9ZKwdF+FJeWofNGEaH4UoPAnhgTyAgk6tNpl6slsbfAQv3jnJfvNspfQANLwR9zXU2Wrck3A0IOvasz54MOgLonBE6EipCyRvounRywAbCZXwCu3Ra3evSHh2jcUDyh6OuYU17BW0JVyplaff7yhO06R2deqEEFdSiWQUweWuhaSgB97aMsUtRx9MQhyj5CkjlYmG+Sq+sPnpCtzDIC/PmNjhi/wsOxinsb4fWvLlWEnELQuO97bbjU4r7DIYrhFOHe86LFufP3BMNOHx9njpo8VZMNLBmBxRwO6x1cYI2y12uD8EOn6HP51GOZ0tdxcsF91YR1NqnuYvIGftfnzU396Llb4p5zX5WcqtyiKR+3vhz4OksH4p3VIGA388AtzE6owLpCWvMav1qkf5lT15oF8XIRohOdks0F+QIQ4vfWbhT1U1qIPZ5SAE6Ayk9XtAEAYcUesgYP5TxWL3tvwG/j8ZONj8W1w=
    ADMIN_USERNAME: AgAHH+2odcJaGByojrsxWyrtOF7P78KvzjH5u65gac3E36pBRxCwvHEIfEtr9EHMAhwpTiNoE3c4abs1OD7M5LZShonkm5PH+zuXatYWKWk2ceSKRmDbcM9MRCoEafXLKnKChUq/k7sU0hqaitknpXpgISO32ps4/2kcKvTdzsKVpg0HoOBcpHaAK7IjReQKKfV/OT0YkPngmKYO3+2jvFdsTA3lMSYzG8yPlBSilGYhQggivPjGFKshsZ9R7h57E3e4pTEl6Do/1Ok/FyDzKodbv3hol3YxL4gWykXxp8cCZo1/v4BGn2rI6RErbN0tSxM26QBNZgXfzmO/KYXA6zZ975lKzP3uVSA5gGGpC45+G3pEfjrska/9qHI9FZxfFJKgcv2ieMcYeCgK2l6RdAGrQnhRe4KuQPXm7rkqZHImoLXN9kM7FsjSwf8nBB9NJeqEcTpS4EYEmux7UOcffK531ihpRZb4kuCnIFfjEELLiGhKyd4fM8i5m53fVc5V+dkbeFbf0FB/QnIJD2xXK5/nybJytBqeYemNha06feaeQMIiOL7+CpccFuDetCYDy9/zSCj1hihROiX890hu2+kVJ603DmI1uqFaUk79VP3Q1WIl/2IvEa6LnVzA/StDLzokpDkGD9kdnKSdxgiBZEuE0I7UGb3e9pIiX+vwMg4LFIfzr60G6UVqbmFKcc4ZIqSQIY48pQ==
  template:
    metadata:
      name: miniflux-admin
      namespace: miniflux
