---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCs5Lp6krxTrOK0/+/5Lbxt6KsTTZHwmPNiJfROBgMF2aSshRNfMuhTh+FPn7JhNweuC8deGxbBgQfLC2FhR2qojwhtp4Bk2NzJWrDnCHxQro7uhTqbDw+mvr/Q0Q0bqBqfUsJe0L/wpUX5CzAk+Mkn9rotLBfd3kdOf80Aq1bvOj8sqkyhtGGfhvgN6h53p+R2jijavP1RVNvZ6oFTCVq+MyHtTUT48DliXO+svL8UWk5p13u2dKrs8XE8JFmcbCQsvheEG/NJGoOq+/XRDxnIYeKIzgatGWm3jKvF5d4l9iEI47JTRvNRs+dDAf5nHMz4fqGMmL5B1QaAw8zHAUv9UzBLU558UbsGSyK/6/6GfZ/AA+s1nSU0Ne2jzQliNs/xe4MoDll/bFfmmFMiVvvlVoQX+knO3SfOVWCQ/3NGOhU3MIXAFyaXdtxnpALZ8NohoqzFW/SukiUh+fN9j9KDaFbvud5ucMYM8DkGwZ8KTZ0A2IQpzXEISbIZ1qPKUPF0JDV9pyV0HLc94SuuuVQNdp21/KY/8NveNbRv/Nj1BJquNlfHbc602LMhbN39o8ONzsdvQRLKh8T7PSMpLSOM0TTh5Cyz46PN87BTYyCBJ1YMIOMCyKsYkRn1Yz8We0gQGYlJMT9bH+K7ZmvYm3oB0Fmh68YJ2MnAaaeuI1WRawVVEumnlDzTmbx12mSJ/Roy680NIO0c5G6h8HI=
    admin-user: AgCj6JURhsyzDa8aVvu1AStdnSIqlWw67x7eaaCTI8zOHZyVIeMHwR8v7jAbsCPuXiznbmGngaU2uBfi34kubPcyZOLXRu2KKEmIJpwWzlOQnJSnV0Or8fc92C1xmbUkxBpbgcOOpyicbzji6QTksKah1tY5yNVClUDHvg+VD2Jee/tANqGKrtcqrqiqmB3IPGcrFzgB2NnZxu9ym0F1CQVhi5rjYWaTFZ2/W/1ByUt3He8zZd6Q5CGwKtGDK3P27u2UAcDDIjpwx5/5q+CouaX9WzHDwWc2Zo0TLY7KqWvM3bjbN4YSuqCyXUfrXbggEAQOwp1IiFdFCjgqh6bYt3XaM3Cd65RAAhXKP61ZQ4w/mn1EofI/kuxrlBHI8ZjoCsb9jrCrvLx0g2XuWdAkYKKUmfbHK27razxJ4iaGzKN2Sbun82wt4EH5FLys3W6nEZ0mhunTnDs8XydhcCmHnSoJW/Nxd7RLCCrShj22zxLztKaO7+JTRSTguTlAchw6IwlQpYiHPeG15GhHq0qtyeOGVUQphRd2vPw2Jnc/VSIqEGZvpHsIp83wpigxtoqpUbJ2SHz6SDTFiIdmqxrGXDVNVcaLteQDcS3AIzHZ6G4r3VI74U6n2oGw6U5ysb0f/kkvIRjfQ2rRfmo7VxFRV7KmiCitL/pDCOnNKNbJNpoF+kTgEbcj0KojJhB8dNECcPxcm6dJwg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
