apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logans-library

resources:
  - sealed-secret.yaml
  - db.yaml
  - app.yaml
  - ingress.yaml

configMapGenerator:
  - name: mariadb-initdb
    files:
      - schema.sql

images:
  - name: ghcr.io/phdbuilds/loganslibrary
    newTag: main
