CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    description TEXT,
    hasread BOOLEAN DEFAULT FALSE,
    dateread DATETIME DEFAULT NULL,
    dateadded DATETIME DEFAULT CURRENT_TIMESTAMP
);
