---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loganslibrary-db
  namespace: logans-library
spec:
  encryptedData:
    MARIADB_PASSWORD: AgCfpGkZmXL6Erko8962rCFVMhIRyVmqvX0YPkT+1Vm9x4s7yckkVnuOunL9KdL8YL36MIInQMOOBr0gZHyFwOszrmdL8Ad0uPRo8DUo6JI+guE2gTqIGduWnGsXLowXXTbaDpUMeFbABa2GjZ/4Wh9AgyIOGIqU72UMC9Ncd5nupjFda4JoSXxq/Xr/KFw4UkDHe59zH6d8lY0wLarY+H1yk2VdGuNfye8z1aT1PT/FEA80ZTt+VsCBXCvlFLHtdQB/y+fOpoiTiFW93y4FJ5H++DVUAEcoo/06J5KjsBVXI6yjNlNtxWkpXCg4ylBNw8FQU3e9C2WR0UKjuqZMlmVR2i0BKb4dD/3eIsILONZFH6GWZK/99ysAtdXAsUNvaa+EZDgAD8t45O9CWPBoZqZGwdUD/6gsczgBkjPcmgCXtCGFpPpLtWPqa8zNn+7duFS9hDLTt9KCj0mtL46MjTkd5b23cnpzHDLJjxG4uG7wGWqhK/PbM+W3XzjZaYBfffMQFpgDeu3qQyLzURaQ8XtO5W0+q7hdQ1WqBIeb/JqNvhNKhUp7TdPREWSjZwgZVEpWt8eGiYlP8ACItqpNvOgk1+KJMyseyyXKzNJHa535O6R5z+x+SYVJj/ODWaBn7UDhsZUFzzsVpIplPUgCuhSc/835Mji2tu+SMUZ4qXkSBfolu3U19l+FBww5VKlV0VhpPxiAFHc1WVfhD+I=
    MARIADB_ROOT_PASSWORD: AgCtNofxp55N8R51whoc2fmM8lMr83OHTH7rg9IJVnO1BjT5t8ARNwKgi4HqXkibvM0p1Puhomlx9Fp/HsIFo4w5N3Zdk/rAXy8zjHn9P5IEIBBx2uI0Zeh4k+aWmizWumR8nntlMVY6VEpRBwFNaipThVGfePjD4JbDDeRRtJF1XUFdZLjV02f0b+HQnmkiOUNhDJ50ml3LEvFUYg/XnuBFcjQ5sHKOYmSMdhWiI2whfZVCGzV7xH5SU7e3i0UcWApLFEECjj27I9jgkDqwNtPUfnAC+nXlgmgwAPcDRDwHjtbt8aNxXMHA79jFTS5v5W4pChIB2aLGRoiX345yyAnuTojIOMQ7OWFpjx8qmgkt4gDgrrJccHVGx10ocx0F/H2g+8BMHSYeH2Ry7jAs4915wRS47Tt7z/VS9ZRcJ8mI+vdeNYx93WYWpoZ6EoAQvEF++UXDzuhwDpix7NcNK7I9P8hcqSVvlX4o0dqjP/fMZNVd4B+w1ykQ6Kyd3shrQWFGkoGnyaaKF+l4Vw3zr3v3BtB55BdAyPHIxLJFjswic4MChQPbQAoNaB3qj6IviwaASdYiIW4D9IxYCNPypylDU/d9v3bwdD0rVwzKk+j+uGIkRNYvbp6QQLT9WCdz4wVI4OQ8SxdMexuySljpF1A50lNaHJSeWLmLJQhz45AkPEZr5lUS69UFG6ZzH/az8oV+Cb/Ir1ThqkNIiLA=
  template:
    metadata:
      name: loganslibrary-db
      namespace: logans-library
