---
all:
  children:
    jumphost:
      hosts:
        sirius:
          ansible_host: 10.0.0.7

    management:
      hosts:
        pulsar:
          ansible_host: 10.0.0.8
        lfs-build:
        pihole:
        hubble:
        alpha-cen:
        proxima-cen:
        vega:

    test:
      hosts:
        test-mgmt:
        test-test:
        test-prod:

    k3s_cluster:
      children:
        k3s_server:
          hosts:
            triangulum-alpha:
        k3s_agent:
          hosts:
            triangulum-beta:
      vars:
        ansible_user: core
        k3s_channel: stable
