---
all:
  children:
    management:
      hosts:
        sirius:
          ansible_host: 10.0.0.187
        ansible-test-mgmt:
          ansible_host: 10.0.0.50
    prod:
      hosts:
        ansible-test-prod:
          ansible_host: 10.10.0.50
    seclab:
      hosts:
        ansible-test-seclab:
          ansible_host: 10.20.0.50
