---
all:
  children:
    jumphost:
      hosts:
        sirius:
          ansible_host: 10.0.0.7

    management:
      hosts:
        pulsar:
          ansible_host: 10.0.0.8
        lfs-build:
        pihole:
        hubble:
        alpha-cen:
        proxima-cen:
        vega:

    test:
      hosts:
        test-mgmt:
        test-test:
        test-prod:

    kthw:
      hosts:
        jumpbox:
          ansible_host: 10.0.0.30
        server:
          ansible_host: 10.0.0.31
        node-0:
          ansible_host: 10.0.0.32
        node-1:
          ansible_host: 10.0.0.33
