apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    theme: dark
    color: slate
    headerStyle: boxed
    background:
      image: https://images.unsplash.com/photo-1502252430442-aac78f397426?q=80&w=1740&auto=format&fit=crop
    cardBlur: 3xl
  custom.css: |
    .services-group h2,
    #bookmarks h2 {
      text-shadow: 0 1px 4px rgba(0, 0, 0, 0.9);
      font-weight: 700;
    }
  custom.js: ""
  bookmarks.yaml: |
    - Sites:
        - home.lab repo:
            - abbr: GH
              href: https://github.com/PhDbuilds/home.lab
        - My Portfolio:
            - abbr: MP
              href: https://spacevoyager.club
        - My Blog:
            - abbr: MB
              href: https://blog.spacevoyager.club
  services.yaml: |
    - Infrastructure:
        - Proxmox VE:
            icon: proxmox.png
            href: "https://192.168.1.180:8006/"
            description: Proxmox VE hypervisor
        - OPNsense:
            icon: opnsense.png
            href: https://10.0.0.1/
            description: OPNsense firewall
        - Pi-hole:
            icon: pi-hole.png
            href: http://pihole.home.lab/admin/login
            description: Pi-hole DNS sinkhole
        - Argo CD:
            icon: argo-cd.png
            href: https://argocd.home.lab/
            description: Prod Argo CD
        - Uptime-kuma:
            icon: uptime-kuma.svg
            href: https://uptime-kuma.home.lab/
            description: Uptime Kuma Monitoring Tool
            widget:
              type: uptimekuma
              url: http://uptime-kuma.monitoring.svc.cluster.local:3001
              slug: home
    - Apps:
        - MiniFlux:
            icon: miniflux.svg
            href: "https://miniflux.home.lab/"
            description: News RSS Feed

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
