apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - clusterrolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml
