- name: Manage cluster entries in /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: kubernetes-the-hard-way"
    block: |
      {% for host in cluster_hosts %}
      {{ host.ip }} {{ host.name }}
      {% endfor %}
