---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: test-secret
  namespace: default
spec:
  encryptedData:
    foo: AgAfJw3cAo1SpY8bOdWXMtwjj6/zP9OVY9Uk42dpFEcuTXKKIzOPiK4erbsm5GDzAz+HD2xQvDhJGvZfEqVblZsOcnhTY/CeGxWFHl0BJbVoqFR3VOMST9/uPltDGfKb5dG9vAPiiEzffwP+3M3L/04PW+EClsNDXfbm0xSPS7WZrwj5uvbdaCjyrr0gMRB7LmjJ9m1UQvC73IxkYSMP7wJnHLn5dkXSPZGDh4r2OEFQbe0+XdwBrwv0eJHZkT+v+SPcBN7Ew093xFoIrfcWNg8bHSZqcNk9uoAT+2YhriLEYsJGDOnA/tnQPCVFzz973aTRqB1aUuiDUjFAZv342MMXXAnU0Ev0Mv2+c4LZBpGHcPHorNVzmtrhCpv78insj4aotSV4Fwkv4h5ssb/PCo4oD+gyoHcd2dK/Yu2KeTbX384aAiKukBAfkbgTts5+qFaffmmGS6zbW9v2eiLO3eame2izUNAKBvb2d0xsOf9YVdClv4JtBl5GYb1MhfKtDLdnEoIbrU+4hlKgXH/w5XFoQ4iVz8Bux9ygvLGGr8aHOPIqGMi48mfvC0nCIHThda3PLtXC0rTU0dK0mUdw8FVfh2yFT3uSGuQ6l+I+fit+/a/AX7b+eifz2fglRWyqaeEfcG2UqbeNvkyZ5kTOpjRogOihtBUxxsf7sQSoDnZUuvuhHXik0pWde1Y0UivtxdSE2r0=
  template:
    metadata:
      name: test-secret
      namespace: default
