---
- name: Configure K3s Agents
  hosts: k3s_agent
  become: true
  vars:
    load_balancer_ip: "10.10.0.107"
  tasks:
    - name: Open flannel VXLAN port
      ansible.posix.firewalld:
        port: 8472/udp
        state: enabled
        permanent: true
        immediate: true

    - name: Open kubelet port
      ansible.posix.firewalld:
        port: 10250/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Install K3s Agent
      shell: |
        curl -sfL https://get.k3s.io | sh -s - agent \
        --server https://{{ load_balancer_ip }}:6443
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_TOKEN: "{{ lookup('ansible.builtin.env', 'K3S_TOKEN') }}"
