---
- name: Configure K3s Servers (HA with Postgres)
  hosts: k3s_server
  become: true
  vars:
    load_balancer_ip: "10.10.0.107"
    vault_k3s: "{{ lookup('community.hashi_vault.vault_kv2_get', 'k3s', mount_point='secret') }}"
  tasks:
    - name: Open k3s API port
      ansible.posix.firewalld:
        port: 6443/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Open k3s metrics port
      ansible.posix.firewalld:
        port: 10250/tcp
        state: enabled
        permanent: true
        immediate: true

    - name: Open flannel VXLAN port
      ansible.posix.firewalld:
        port: 8472/udp
        state: enabled
        permanent: true
        immediate: true

    - name: Install K3s Server
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
        --node-taint CriticalAddonsOnly=true:NoExecute \
        --tls-san {{ load_balancer_ip }}
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_DATASTORE_ENDPOINT: "{{ vault_k3s.secret.k3s_datastore_endpoint }}"
        K3S_TOKEN: "{{ vault_k3s.secret.k3s_token }}"
