---
- name: Configure K3s Agents
  hosts: k3s_agent
  become: true
  vars:
    load_balancer_ip: "10.10.0.107"
    vault_k3s: "{{ lookup('community.hashi_vault.vault_kv2_get', 'k3s', mount_point='secret') }}"
  tasks:
- name: Open required ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - 8472/udp    # flannel VXLAN
        - 10250/tcp   # kubelet
        - 9100/tcp    # node-exporter

    - name: Install K3s Agent
      shell: |
        curl -sfL https://get.k3s.io | sh -s - agent \
        --server https://{{ load_balancer_ip }}:6443
      args:
        creates: /usr/local/bin/k3s
      environment:
        K3S_TOKEN: "{{ vault_k3s.secret.k3s_token }}"
