apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logans-library
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/phdbuilds/home.lab.git
    targetRevision: master
    path: gitops/manifests/logans-library
  destination:
    server: https://kubernetes.default.svc
    namespace: logans-library
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
