apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://sirius.home.lab:8443/acme/acme/directory
    email: blnorris777@gmail.com
    privateKeySecretRef:
      name: step-ca-account-key
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJxRENDQVUyZ0F3SUJBZ0lRUFY1ZllmeWtJZUM3Yk84WFMzcmhZekFLQmdncWhrak9QUVFEQWpBeU1STXcKRVFZRFZRUUtFd3BJYjIxbFRHRmlVRXRKTVJzd0dRWURWUVFERXhKSWIyMWxUR0ZpVUV0SklGSnZiM1FnUTBFdwpIaGNOTWpZd05URTFNVGMwT1RVMldoY05Nell3TlRFeU1UYzBPVFUyV2pBeU1STXdFUVlEVlFRS0V3cEliMjFsClRHRmlVRXRKTVJzd0dRWURWUVFERXhKSWIyMWxUR0ZpVUV0SklGSnZiM1FnUTBFd1dUQVRCZ2NxaGtqT1BRSUIKQmdncWhrak9QUU1CQndOQ0FBU3ZCTFk4NFNPVEpBUUZyZWJNblhrcTJRY2tkbXRDTDJ6YVQzYXhEK1VuQmN1SQprSVJFa3kzT2VUM2ZQZENXcXVZSVMycXNhTzB1dmhrdmZQbTBlZ3A3bzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBVEFkQmdOVkhRNEVGZ1FVWWptSUNVdjJYMGtqQXROdFVEMEcKajh4ZEF0Y3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTnlnRkEveEFldTVXWHJpcmtnQ2xZMHBMSFhyY2poUgpKSlJ4ekRxTS9PWkhBaUVBanA5NTVmc2Uxdm1TUjYvcERxVUMxSUZ5Nm1nUVhPWG1GVmxWZUJQMGc2WT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
